"""empty message

Revision ID: 0362e45eba0c
Revises: b86c9b6ae6b2
Create Date: 2024-12-03 15:15:17.135013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0362e45eba0c'
down_revision = 'b86c9b6ae6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
